version: "3.1"
services:
  web_api:
    image: nginx:1.15
    container_name: web_api
    working_dir: /var/www
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./dev/nginx/conf.d/site.conf:/etc/nginx/conf.d/default.conf

  db_api:
    image: mysql:5.7
    container_name: db_api
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
      - MYSQL_USER=chip
      - MYSQL_PASSWORD=ZF8WaFhf

  php_api:
#    build: phpdocker/php-fpm
#    build: dockerwest/php-symfony:7.2
    image: dockerwest/php-symfony:7.2
    container_name: php_api
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=dev
      - DEVELOPMENT=1

  npm_api:
    image: catchdigital/node-sass:8.12.0-alpine
    container_name: npm_api
    working_dir: /var/www
    volumes:
      - ./:/var/www

